### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()
tienda2.head()
tienda3.head()
tienda4.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Lavavajillas,Electrodomésticos,1084800.0,56000.0,11/11/2022,Rafael Acosta,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175
1,Cama box,Muebles,473800.0,25400.0,03/01/2020,Izabela de León,Cúcuta,5,Tarjeta de crédito,2,7.89391,-72.50782
2,Balón de baloncesto,Deportes y diversión,23700.0,0.0,25/12/2022,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
3,Modelado predictivo,Libros,57700.0,1300.0,23/11/2021,Lucas Olivera,Medellín,3,Nequi,1,6.25184,-75.56359
4,Auriculares,Electrónicos,138900.0,5600.0,25/04/2022,Blanca Ramirez,Bogotá,4,Tarjeta de crédito,7,4.60971,-74.08175

#1. Análisis de facturación

In [3]:
#print(tienda.columns)
#Suma ventas totales tienda
tienda["Precio"] = pd.to_numeric(tienda["Precio"], errors="coerce")
ventas_totales = int(tienda["Precio"].sum())

#Suma ventas totales tienda2
tienda2["Precio"] = pd.to_numeric(tienda2["Precio"], errors="coerce")
ventas_totales2 = int(tienda2["Precio"].sum())

#Suma ventas totales tienda3
tienda3["Precio"] = pd.to_numeric(tienda3["Precio"], errors="coerce")
ventas_totales3 = int(tienda3["Precio"].sum())

#Suma ventas totales tienda4
tienda4["Precio"] = pd.to_numeric(tienda4["Precio"], errors="coerce")
ventas_totales4 = int(tienda4["Precio"].sum())

print("Ventas totales tienda 1:", ventas_totales)
print("Ventas totales tienda 2:", ventas_totales2)
print("Ventas totales:tienda 3", ventas_totales3)
print("Ventas totales:tienda 4", ventas_totales4)

ventas_por_tienda = {
    "Tienda 1": ventas_totales,
    "Tienda 2": ventas_totales2,
    "Tienda 3": ventas_totales3,
    "Tienda 4": ventas_totales4
}

df_ventas = pd.DataFrame(list(ventas_por_tienda.items()), columns=["Tienda", "Facturacion"])
df_ventas_ordenado = df_ventas.sort_values(by="Facturacion", ascending=False)
print(df_ventas_ordenado)

Ventas totales tienda 1: 1150880400
Ventas totales tienda 2: 1116343500
Ventas totales:tienda 3 1098019600
Ventas totales:tienda 4 1038375700
     Tienda  Facturacion
0  Tienda 1   1150880400
1  Tienda 2   1116343500
2  Tienda 3   1098019600
3  Tienda 4   1038375700

# 2. Ventas por categoría

In [4]:
ventas_por_categoria = tienda["Categoría del Producto"].value_counts()
print("Cantidad vendida de cada categoria en tienda1:")
print(ventas_por_categoria)

ventas_por_categoria2 = tienda2["Categoría del Producto"].value_counts()
print("Cantidad vendida de cada categoria en tienda2:")
print(ventas_por_categoria2)

ventas_por_categoria3 = tienda3["Categoría del Producto"].value_counts()
print("Cantidad vendida de cada categoria en tienda3:")
print(ventas_por_categoria3)

ventas_por_categoria4 = tienda4["Categoría del Producto"].value_counts()
print("Cantidad vendida de categoria producto en tienda4:")
print(ventas_por_categoria4)

Cantidad vendida de cada categoria en tienda1:
Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64
Cantidad vendida de cada categoria en tienda2:
Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: count, dtype: int64
Cantidad vendida de cada categoria en tienda3:
Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Instrumentos musicales     177
Artículos para el hogar    177
Name: count, dtype: int64
Cantidad vendida de categoria producto en tienda4:
Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: count, dtype: int64

# 3. Calificación promedio de la tienda

In [27]:
#print(tienda.columns)
#len(tienda)

In [5]:
#Calificación promedio tienda
tienda["Calificación"] = pd.to_numeric(tienda["Calificación"], errors="coerce")
suma_calificaciones = int(tienda["Calificación"].sum())
promedio_cali_tienda = suma_calificaciones / len(tienda)

#Calificación promedio tienda2
tienda2["Calificación"] = pd.to_numeric(tienda2["Calificación"], errors="coerce")
suma_calificaciones2 = int(tienda2["Calificación"].sum())
promedio_cali_tienda2 = suma_calificaciones2 / len(tienda2)

#Calificación promedio tienda3
tienda3["Calificación"] = pd.to_numeric(tienda3["Calificación"], errors="coerce")
suma_calificaciones3 = int(tienda3["Calificación"].sum())
promedio_cali_tienda3 = suma_calificaciones3 / len(tienda3)

#Calificación promedio tienda4
tienda4["Calificación"] = pd.to_numeric(tienda4["Calificación"], errors="coerce")
suma_calificaciones4 = int(tienda4["Calificación"].sum())
promedio_cali_tienda4 = suma_calificaciones4 / len(tienda4)

print("Promedio de calificaciones tienda 1:", promedio_cali_tienda)
print("Promedio de calificaciones tienda 2:", promedio_cali_tienda2)
print("Promedio de calificaciones tienda 3:", promedio_cali_tienda3)
print("Promedio de calificaciones tienda 4:", promedio_cali_tienda4)

calificaciones_por_tienda = {
    "Tienda 1": promedio_cali_tienda,
    "Tienda 2": promedio_cali_tienda2,
    "Tienda 3": promedio_cali_tienda3,
    "Tienda 4": promedio_cali_tienda4
}

df_calificaciones = pd.DataFrame(list(calificaciones_por_tienda.items()), columns=["Tienda", "Calificacion_Promedio"])
df_calificaciones_ordenado = df_calificaciones.sort_values(by="Calificacion_Promedio", ascending=False)
print(df_calificaciones_ordenado)

Promedio de calificaciones tienda 1: 3.976685036032217
Promedio de calificaciones tienda 2: 4.037303942348453
Promedio de calificaciones tienda 3: 4.048325561678677
Promedio de calificaciones tienda 4: 3.9957591178965224
     Tienda  Calificacion_Promedio
2  Tienda 3               4.048326
1  Tienda 2               4.037304
3  Tienda 4               3.995759
0  Tienda 1               3.976685

# 4. Productos más y menos vendidos

In [11]:
ventas_por_producto = tienda["Producto"].value_counts()
print("Cantidad vendida de cada producto en tienda1:")
print(ventas_por_producto)

ventas_por_producto2 = tienda2["Producto"].value_counts()
print("Cantidad vendida de cada producto en tienda2:")
print(ventas_por_producto2)

ventas_por_producto3 = tienda3["Producto"].value_counts()
print("Cantidad vendida de cada producto en tienda3:")
print(ventas_por_producto3)

ventas_por_producto4 = tienda4["Producto"].value_counts()
print("Cantidad vendida de cada producto en tienda4:")
print(ventas_por_producto4)

Cantidad vendida de cada producto en tienda1:
Producto
Microondas                     60
TV LED UHD 4K                  60
Armario                        60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Vaso térmico                   54
Refrigerador                   54
Impresora                      54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Lavadora de ropa               47
Guitarra eléctrica             47
Guitarra acústica              46
Sofá reclinable                46
Silla de oficina               46
Estufa                         45
Cama box                       44
Kit de bancas                  44
Smart TV                       44
Cama king                      44
Cubo mágico 8x8                44
Mesa de centro                 44
Set de ollas                   43
Smartwatch                     43
Juego de mesa                  43
Balón de voleibol              42
Dashboards con Power BI        42
Tablet ABXY                    42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Muñeca bebé                    40
Mesa de comedor                40
Dinosaurio Rex                 40
Cuerda para saltar             40
Mochila                        39
Ciencia de datos con Python    39
Pandereta                      36
Olla de presión                35
Auriculares con micrófono      33
Celular ABXY                   33
Name: count, dtype: int64
Cantidad vendida de cada producto en tienda2:
Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Guitarra acústica              58
Pandereta                      58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Silla de oficina               49
Refrigerador                   49
Muñeca bebé                    48
Carrito de control remoto      47
Guitarra eléctrica             47
Cama box                       47
Vaso térmico                   47
Modelado predictivo            46
Balón de voleibol              46
Set de vasos                   46
Lavavajillas                   46
Kit de bancas                  45
Cama king                      45
Bicicleta                      45
Mochila                        45
Cubo mágico 8x8                45
Ajedrez de madera              45
Mesa de centro                 45
TV LED UHD 4K                  45
Tablet ABXY                    44
Smartwatch                     44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Sofá reclinable                44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Estufa                         42
Dinosaurio Rex                 42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Mesa de comedor                34
Impresora                      34
Juego de mesa                  32
Name: count, dtype: int64
Cantidad vendida de cada producto en tienda3:
Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Estufa                         53
Cuerda para saltar             53
Modelado predictivo            53
Carrito de control remoto      52
Lavavajillas                   52
Bicicleta                      52
Juego de mesa                  52
Pandereta                      51
Impresora                      50
Refrigerador                   50
Balón de baloncesto            50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Sillón                         47
Guitarra acústica              47
Olla de presión                47
Ajedrez de madera              47
Ciencia de datos con Python    46
Iphone 15                      46
Dinosaurio Rex                 46
Silla de oficina               46
Smartwatch                     46
Cama box                       46
Iniciando en programación      46
Secadora de ropa               45
Sofá reclinable                45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
TV LED UHD 4K                  42
Mesa de centro                 42
Lavadora de ropa               42
Batería                        41
Dashboards con Power BI        40
Cubertería                     39
Muñeca bebé                    39
Auriculares con micrófono      39
Asistente virtual              39
Vaso térmico                   38
Guitarra eléctrica             38
Set de vasos                   36
Mochila                        36
Microondas                     36
Bloques de construcción        35
Name: count, dtype: int64
Cantidad vendida de cada producto en tienda4:
Producto
Cama box                       62
Cubertería                     59
Dashboards con Power BI        56
Cama king                      56
Carrito de control remoto      55
Mesa de comedor                55
Mesa de noche                  55
Smart TV                       54
Bloques de construcción        54
Pandereta                      52
Impresora                      50
Modelado predictivo            50
Asistente virtual              50
Set de ollas                   50
Balón de baloncesto            50
Vaso térmico                   48
Iphone 15                      48
Muñeca bebé                    48
Batería                        48
Balón de voleibol              48
Juego de mesa                  48
Microondas                     48
Estufa                         47
Cubo mágico 8x8                47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Tablet ABXY                    45
Sillón                         45
Bicicleta                      45
Mesa de centro                 44
Auriculares                    44
Lavavajillas                   43
Cuerda para saltar             43
Iniciando en programación      43
Mochila                        43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Secadora de ropa               40
Silla de oficina               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Refrigerador                   38
Ciencia de datos con Python    38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: count, dtype: int64

# 5. Envío promedio por tienda

In [7]:
print(tienda.columns)
#len(tienda)

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

In [8]:
#Costo de envío tienda
tienda["Costo de envío"] = pd.to_numeric(tienda["Costo de envío"], errors="coerce")
suma_costo_envio = int(tienda["Costo de envío"].sum())
promedio_costo_envio = suma_costo_envio / len(tienda)

#Costo de envío tienda2
tienda2["Costo de envío"] = pd.to_numeric(tienda2["Costo de envío"], errors="coerce")
suma_costo_envio2 = int(tienda2["Costo de envío"].sum())
promedio_costo_envio2 = suma_costo_envio2 / len(tienda2)

#Costo de envío tienda3
tienda3["Costo de envío"] = pd.to_numeric(tienda3["Costo de envío"], errors="coerce")
suma_costo_envio3 = int(tienda3["Costo de envío"].sum())
promedio_costo_envio3 = suma_costo_envio3 / len(tienda3)

#Costo de envío tienda4
tienda4["Costo de envío"] = pd.to_numeric(tienda4["Costo de envío"], errors="coerce")
suma_costo_envio4 = int(tienda4["Costo de envío"].sum())
promedio_costo_envio4 = suma_costo_envio4 / len(tienda4)

print("Promedio de costos de envio tienda 1:", promedio_costo_envio)
print("Promedio de costos de envio tienda 2:", promedio_costo_envio2)
print("Promedio de costos de envio tienda 3:", promedio_costo_envio3)
print("Promedio de costos de envio tienda 4:", promedio_costo_envio4)

costos_envios_por_tienda = {
    "Tienda 1": promedio_costo_envio,
    "Tienda 2": promedio_costo_envio2,
    "Tienda 3": promedio_costo_envio3,
    "Tienda 4": promedio_costo_envio4
}

df_costos_envios = pd.DataFrame(list(costos_envios_por_tienda.items()), columns=["Tienda", "promedio_costo_envio"])
df_costos_envios_ordenado = df_costos_envios.sort_values(by="promedio_costo_envio", ascending=False)
print(df_costos_envios_ordenado)

Promedio de costos de envio tienda 1: 26018.60958033065
Promedio de costos de envio tienda 2: 25216.235693090293
Promedio de costos de envio tienda 3: 24805.680373039424
Promedio de costos de envio tienda 4: 23459.457167090754
     Tienda  promedio_costo_envio
0  Tienda 1          26018.609580
1  Tienda 2          25216.235693
2  Tienda 3          24805.680373
3  Tienda 4          23459.457167

In [10]:

datos = {
    "Tienda": ["Tienda 1", "Tienda 2", "Tienda 3", "Tienda 4"],
    "Facturación Total": [ventas_totales, ventas_totales2, ventas_totales3, ventas_totales4],
    "Calificación Promedio": [promedio_cali_tienda, promedio_cali_tienda2, promedio_cali_tienda3, promedio_cali_tienda4],
    "Gasto Prom. Envío": [promedio_costo_envio, promedio_costo_envio2, promedio_costo_envio3, promedio_costo_envio4],
    #"Diversidad de Ventas": ["Alta", "Baja", "Alta", "Media"],
    #"Concentración Categoría": ["Equilibrada", "Muy alta", "Equilibrada", "Moderada"]
}
print("Tabla comparativa de las tiendas:")
df_comparativa = pd.DataFrame(datos)
print(df_comparativa)

Tabla comparativa de las tiendas:
     Tienda  Facturación Total  Calificación Promedio  Gasto Prom. Envío
0  Tienda 1         1150880400               3.976685       26018.609580
1  Tienda 2         1116343500               4.037304       25216.235693
2  Tienda 3         1098019600               4.048326       24805.680373
3  Tienda 4         1038375700               3.995759       23459.457167